###端口号
server:
  port: 8082

###eureka配置
eureka:
  instance:
    hostname: node3
  client:
    #表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    #表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    #设置与Eureka Server交互的地址，查询服务和注册服务都依赖该地址，多个地址使用','分隔
    service-url:
      defaultZone: http://node1:8080/eureka/,http://node2:8081/eureka/

  server:
    #关闭自我保护,（当一定时间内没有收到某个微服务实例的心跳时，不会注销这个微服务）
    enable-self-preservation: false