###应用名称
spring:
  application:
    name: spring-cloud-eureka-producer
  # zipkin配置
  zipkin:
    base-url: http://118.25.222.167:9411/
  sleuth:
    sampler:
      # 采样率，为1表示全部的请求都进行采样
      probability: 1.0
###端口号
server:
  port: 9000

###eureka配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

  server:
    #关闭自我保护,（当一定时间内没有收到某个微服务实例的心跳时，不会注销这个微服务）
    enable-self-preservation: false